language: bash
services:
- docker
env:
  global:
  - DEPLOY_USER=travis
  - MASTER_SERVER=159.89.174.247
  - MASTER_DOMAIN=ultraselect.me
  - DEV_SERVER=159.89.174.247
  - DEV_DOMAIN=dev.ultraselect.me
  - secure: "s8R8MpPg3Vo6QDGiZBKj1Eb10qfJ5+g2K08r0vEnIpvEYsho16CNtg6a6UfZ6L9UJHFww0Ru7qtAn3g2+drdfjAeGhJWvopA9ktur9oVSQSI+iL/FvmeCmx5EvAbEU/Nrw/SeRYtXAe3jlaV/C+PU2wWxBR5B5YhlQhU0h5axQelqujM2VFtGolSC/aap2Dc1sFjatGsbvn9cY2nF0e7V0408wT0IjNQK5/w3DG09x4wGxKIpyI7ZFzdgqKTzJqIOlbOMxDSulUp5x+5XBpAE2pf0pVcnrPnsTVKoQalZP+nbHd6Vk1cut1CHJksKkNWCEerunA/7T+/aB63ArWtmVvUTLnLG9ULck/rbROWV3mFRoYMdWxt/NyiN8NnPnz5zb0HJU0n3R9pMbc6e4kFELeTbFzNVqcLyEh+JAPYWMc2pg9oLEJHQkP+iJ8oVDOWX/nqKkgN2Al+x2AwbARZnfB2J8FlaWgJdAomlY8Qm/X04GePZBhIlDFkKEdSstBhcWA9eY+RnaBzax4swW/khkm+3l9YY2dor26dRKdaqXIsaF3N5KEwUjVbgYosMZuQAbEbjBwhrf6x46S+sLZAr6iKjn3/oLQc9eI68xmpjRXVUZnbVCPtLeC5bfBxs0q5enV62RDXkJSSR9tsZ/IO9O/5JFXTl+E4MfAT7lafI3k="

before_install:
- openssl aes-256-cbc -K $encrypted_7226a3f085d7_key -iv $encrypted_7226a3f085d7_iv
  -in travis_rsa.enc -out travis_rsa -d
before_script:
- "./travis/docker-build.sh"
script:
- "./travis/drupal-build.sh"
after_success:
- chmod 600 travis_rsa
- eval 'ssh-agent -s'
- ssh-add travis_rsa
- "./travis/deploy.sh"
